### ISSUE TITLE
Create option to backup room's code on server

### ISSUE THREAD

**Issue by t-mullen** [RationalCoding/multihack-server#1]
For private instances.

**Comment by t-mullen** [comment]
Closed in favour of the future <s>**multihack-headless**</s> **multihack-cli**

**Comment by kifhan** [comment]
I'm using `chrome --headless --remote-debugging-port=9222` to sync project background.
Use it as node.js child process with chrome-remote-interface.
Cause phantom.js doesn't support webrtc.
How about you?

**Comment by t-mullen** [comment]
So you run a headless browser with multihack-web to persist your project? That's a clever idea, but not really what I mean.

multihack-headless is going to be a Node client that will use the actual file system instead of the in-browser memory. It'll let you use Multihack to instantly deploy projects instead of just working on them. 

For example, you could run the headless client on a machine running a webserver and be able to serve the files as you edited them. Pretty cool eh?

You'll also be able to use it for persistent storage like you are doing with the headless browser, but without the overhead of the browser. It also won't keep the whole project in-memory.

**Comment by t-mullen** [comment]
Maybe "headless" isn't the best name for it. It should be called "multihack-cli" or something.
